apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pythonweb
spec:
  selector:
    matchLabels:
      app: pythonweb
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: pythonweb
    spec:
      containers:
      - name: pythonweb
        #image: 998252513391.dkr.ecr.us-east-1.amazonaws.com/webapp:0.1.1.88
        image: muritala/pythonapp        
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pythonweb-svc
  labels:
    app: pythonweb
spec:
  selector:
    app: pythonweb
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31200